window.SITE_INDEX = [
  { url: "/", group: "トップ", title: "Gugen株式会社", text: "人は、まだ進化できる。企業のAI活用を、要件定義から実装・社内定着まで伴走します。" },
  { url: "/news/", group: "ニュース", title: "お知らせ", text: "Gugenからの最新のお知らせ・リリース・イベント情報と、よくあるご質問" },
  { url: "/philosophy/", group: "理念・ビジョン・戦略", title: "理念・ビジョン・戦略", text: "人は、まだ進化できる。経営理念、Vision、Values、Culture" },
  { url: "/philosophy/corporate_philosophy.html", group: "理念・ビジョン・戦略", title: "経営理念", text: "人は、まだ進化できる。" },
  { url: "/philosophy/vision.html", group: "理念・ビジョン・戦略", title: "ビジョン", text: "誰もが未来の創り手として生きる時代へ。" },
  { url: "/philosophy/value.html", group: "理念・ビジョン・戦略", title: "バリュー", text: "深観 造形 逆算 試斬 美勝" },
  { url: "/philosophy/identity.html", group: "理念・ビジョン・戦略", title: "ロゴに込めた想い", text: "見えないものを受け取り、手を動かし、現実にする。" },
  { url: "/philosophy/message.html", group: "理念・ビジョン・戦略", title: "代表挨拶", text: "郷 由稀斗 三島 大毅" },
  { url: "/services/", group: "事業セグメント", title: "サービス", text: "Gugen OS Gugen AX Gugen Lab 人間知能・意識研究所" },
  { url: "/services/os.html", group: "事業セグメント", title: "Gugen OS", text: "つくる / AI実装" },
  { url: "/services/ax.html", group: "事業セグメント", title: "Gugen AX", text: "変える / 組織変革" },
  { url: "/services/lab.html", group: "事業セグメント", title: "Gugen Lab", text: "学生・若手向けAIコミュニティ" },
  { url: "/services/research.html", group: "事業セグメント", title: "人間知能・意識研究所", text: "人とAIの関係を問い直す研究開発機関" },
  { url: "/works/", group: "事業セグメント", title: "プロジェクト・実績", text: "AI受託開発 Gugen OS による導入事例" },
  { url: "/articles/", group: "記事", title: "記事一覧", text: "Gugen のビジョン、エンジニアリング、現場の知見" },
  { url: "/careers/", group: "採用", title: "学生と、会社をつくる", text: "2026年7月設立、4人の会社です。いま募集しているのはインターンだけ。" },
  { url: "/careers/apply.html", group: "採用", title: "応募する", text: "応募書類を提出してください。" },
  { url: "/about/", group: "企業情報", title: "会社案内", text: "経営理念、Vision、Values、Cultureと会社情報" },
  { url: "/about/profile.html", group: "企業情報", title: "会社概要", text: "Gugen株式会社 東京都千代田区麹町" },
  { url: "/about/officer.html", group: "企業情報", title: "役員一覧", text: "郷 由稀斗 三島 大毅" },
  { url: "/contact/", group: "企業情報", title: "お問い合わせ", text: "info@gugenlab.com" },
  { url: "/casual-meeting/", group: "企業情報", title: "カジュアル面談", text: "まずは話を聞いてみたい" },
  { url: "/privacy/", group: "企業情報", title: "プライバシーポリシー", text: "個人情報の保護" },
  { url: "/security/", group: "企業情報", title: "セキュリティ", text: "セキュリティ・バイ・デザイン" },
  { url: "/legal/", group: "企業情報", title: "決算公告", text: "会社法第440条" },
  { url: "/legal/transactions.html", group: "企業情報", title: "特定商取引法に基づく表記", text: "特定商取引法第 11 条" },
  { url: "/company/", group: "会社情報", title: "会社情報", text: "人は、まだ進化できる。" },
  { url: "/company/info/", group: "会社情報", title: "会社概要", text: "Gugen株式会社 東京都千代田区麹町" },
  { url: "/company/philosophy/", group: "会社情報", title: "Gugenのカタチ", text: "人は、まだ進化できる。" },
  { url: "/company/leaders/", group: "会社情報", title: "Leaders", text: "郷 由稀斗 三島 大毅" },
  { url: "/company/message/", group: "会社情報", title: "メッセージ", text: "代表挨拶" },
  { url: "/company/access/", group: "会社情報", title: "アクセス", text: "千代田区麹町" },
  { url: "/service/", group: "サービス", title: "サービス", text: "Gugen OS Gugen AX Gugen Lab" },
  { url: "/technology/", group: "テクノロジー", title: "テクノロジー", text: "プロトコル化 LLM RAG" },
  { url: "/recruit/", group: "採用情報", title: "採用情報", text: "学生と、会社をつくる" }
];
